### ISSUE TITLE
training error

### ISSUE THREAD

**Issue by kingulight** [facebookresearch/fairseq-lua#21]
I have re-installed torch and dependency libraries. But I met the thread errors at the beginning of the training. Command are as follows:
fairseq train -sourcelang de -targetlang en -datadir data-bin/iwslt14.tokenized.de-en \
>   -model fconv -nenclayer 4 -nlayer 3 -dropout 0.2 -optim nag -lr 0.25 -clip 0.1 \
>   -momentum 0.99 -timeavg -bptt 0 -savedir trainings/fconv

Error are as follows:

In 3 module of nn.Sequential:
In 2 module of nn.Sequential:
In 1 module of nn.ConcatTable:
In 2 module of nn.Sequential:
In 1 module of nn.Sequential:
...rch/install/share/lua/5.1/tbc/TemporalConvolutionTBC.lua:44: attempt to index field 'TBC' (a nil value)
stack traceback:
	...rch/install/share/lua/5.1/tbc/TemporalConvolutionTBC.lua:44: in function 'updateOutput'
	...din/public/torch/install/share/lua/5.1/nn/WeightNorm.lua:115: in function <...din/public/torch/install/share/lua/5.1/nn/WeightNorm.lua:111>
	[C]: in function 'xpcall'
	...odin/public/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
	...din/public/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function <...din/public/torch/install/share/lua/5.1/nn/Sequential.lua:41>
	[C]: in function 'xpcall'
	...odin/public/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
	...din/public/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function <...din/public/torch/install/share/lua/5.1/nn/Sequential.lua:41>
	[C]: in function 'xpcall'
	...odin/public/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
	...
	...n/public/torch/install/share/lua/5.1/nngraph/gmodule.lua:380: in function 'func'
	...n/public/torch/install/share/lua/5.1/nngraph/gmodule.lua:345: in function 'neteval'
	...n/public/torch/install/share/lua/5.1/nngraph/gmodule.lua:380: in function 'forward'
	...hare/lua/5.1/fairseq/torchnet/ResumableDPOptimEngine.lua:356: in function <...hare/lua/5.1/fairseq/torchnet/ResumableDPOptimEngine.lua:333>
	[C]: in function 'xpcall'
	...n/public/torch/install/share/lua/5.1/threads/threads.lua:234: in function 'callback'
	...din/public/torch/install/share/lua/5.1/threads/queue.lua:65: in function <...din/public/torch/install/share/lua/5.1/threads/queue.lua:41>
	[C]: in function 'pcall'
	...din/public/torch/install/share/lua/5.1/threads/queue.lua:40: in function 'dojob'
	[string "  local Queue = require 'threads.queue'..."]:13: in main chunk

WARNING: If you see a stack trace below, it doesn't point to the place where this error occurred. Please use only the one above.
stack traceback:
	[C]: in function 'error'
	...odin/public/torch/install/share/lua/5.1/nn/Container.lua:67: in function 'rethrowErrors'
	...din/public/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'func'
	...n/public/torch/install/share/lua/5.1/nngraph/gmodule.lua:345: in function 'neteval'
	...n/public/torch/install/share/lua/5.1/nngraph/gmodule.lua:380: in function 'func'
	...n/public/torch/install/share/lua/5.1/nngraph/gmodule.lua:345: in function 'neteval'
	...n/public/torch/install/share/lua/5.1/nngraph/gmodule.lua:380: in function 'forward'
	...hare/lua/5.1/fairseq/torchnet/ResumableDPOptimEngine.lua:356: in function <...hare/lua/5.1/fairseq/torchnet/ResumableDPOptimEngine.lua:333>
	[C]: in function 'xpcall'
	...n/public/torch/install/share/lua/5.1/threads/threads.lua:234: in function 'callback'
	...din/public/torch/install/share/lua/5.1/threads/queue.lua:65: in function <...din/public/torch/install/share/lua/5.1/threads/queue.lua:41>
	[C]: in function 'pcall'
	...din/public/torch/install/share/lua/5.1/threads/queue.lua:40: in function 'dojob'
	[string "  local Queue = require 'threads.queue'..."]:13: in main chunk
stack traceback:
	[C]: in function 'error'
	...n/public/torch/install/share/lua/5.1/threads/threads.lua:183: in function 'dojob'
	...n/public/torch/install/share/lua/5.1/threads/threads.lua:264: in function 'synchronize'
	...hare/lua/5.1/fairseq/torchnet/ResumableDPOptimEngine.lua:371: in function 'doTrain'
	...hare/lua/5.1/fairseq/torchnet/ResumableDPOptimEngine.lua:189: in function 'train'
	...ic/torch/install/share/lua/5.1/fairseq/scripts/train.lua:405: in main chunk
	[C]: in function 'require'
	...rch/install/lib/luarocks/rocks/fairseq/scm-1/bin/fairseq:17: in main chunk
	[C]: at 0x004064a0

**Comment by kingulight** [comment]
The problem is solved by install tbc as follows:
luarocks install tbc

**Comment by rahular** [comment]
I am still facing this issue. `tbc` is already installed. Any pointers?
