### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by duyvuleo** [facebookresearch/fairseq-lua#4]
Hi,

I tried to install fairseq but failed with the below error message. It seems that the server I am using is missing OpenBLAS which is required to install torch/tds library. However, I am not a sudoer to install OpenBLAS on /opt/OpenBLAS. Is there any way to install OpenBLAS locally and link it to luarocks? Thanks!

> Missing dependencies for fairseq:
> torchnet 
> visdom 
> torchnet-sequential 
> tbc 
> nccl 
> tds 
> 
> Using https://raw.githubusercontent.com/torch/rocks/master/torchnet-scm-1.rockspec... switching to 'build' mode
> 
> Missing dependencies for torchnet:
> tds >= 1.0
> 
> Using https://raw.githubusercontent.com/torch/rocks/master/tds-scm-1.rockspec... switching to 'build' mode
> Cloning into 'tds'...
> remote: Counting objects: 32, done.
> remote: Compressing objects: 100% (29/29), done.
> remote: Total 32 (delta 5), reused 10 (delta 1), pack-reused 0
> Receiving objects: 100% (32/32), 23.14 KiB | 0 bytes/s, done.
> Resolving deltas: 100% (5/5), done.
> Checking connectivity... done.
> -- The C compiler identification is GNU 5.4.0
> -- The CXX compiler identification is GNU 5.4.0
> -- Check for working C compiler: /usr/bin/cc
> -- Check for working C compiler: /usr/bin/cc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Check for working CXX compiler: /usr/bin/c++
> -- Check for working CXX compiler: /usr/bin/c++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Found Torch7 in /home/vhoang2/torch/install
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /tmp/luarocks_tds-scm-1-9010/tds/build.luarocks
> Scanning dependencies of target tds
> [ 16%] Building C object CMakeFiles/tds.dir/tds_utils.c.o
> [ 33%] Building C object CMakeFiles/tds.dir/tds_elem.c.o
> [ 50%] Building C object CMakeFiles/tds.dir/tds_hash.c.o
> [ 66%] Building C object CMakeFiles/tds.dir/tds_vec.c.o
> [ 83%] Building C object CMakeFiles/tds.dir/tds_atomic_counter.c.o
> make[2]: *** No rule to make target '/opt/OpenBLAS/lib/libopenblas.so', needed by 'libtds.so'.  Stop.
> CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/tds.dir/all' failed
> make[1]: *** [CMakeFiles/tds.dir/all] Error 2
> Makefile:127: recipe for target 'all' failed
> make: *** [all] Error 2
> 
> Error: Failed installing dependency: https://raw.githubusercontent.com/torch/rocks/master/torchnet-scm-1.rockspec - Failed installing dependency: https://raw.githubusercontent.com/torch/rocks/master/tds-scm-1.rockspec - Build error: Failed building.
>

**Comment by jgehring** [comment]
You should be able to simply install OpenBLAS to a local prefix (e.g. ~/torch/install) and add the include/ and lib/ paths to CMAKE_LIBRARY_PATH. Please let me know if this works.

**Comment by lqfarmer** [comment]
I meet the same problem.could you tell me how to add the include/ and lib/ paths to CMAKE_LIBRARY_PATH. Thank you !

**Comment by lqfarmer** [comment]
@jgehring ，I meet the same problem·，I try the method you mentioned above, but same problem occur.
[@nmyjs_160_20 fairseq]# export CMAKE_LIBRARY_PATH=$CMAKE_LIBRARY_PATH:/root/torch/install/include:/root/torch/install/lib
[@nmyjs_160_20 fairseq]# luarocks make rocks/fairseq-cpu-scm-1.rockspec

Missing dependencies for fairseq-cpu:
tbc 

Using https://raw.githubusercontent.com/torch/rocks/master/tbc-scm-1.rockspec... switching to 'build' mode
\u6b63\u514b\u9686\u5230 'TemporalConvolutionTBC'...
remote: Counting objects: 22, done.
remote: Compressing objects: 100% (20/20), done.
remote: Total 22 (delta 2), reused 7 (delta 0), pack-reused 0
\u63a5\u6536\u5bf9\u8c61\u4e2d: 100% (22/22), 12.48 KiB | 0 bytes/s, done.
\u5904\u7406 delta \u4e2d: 100% (2/2), done.
cmake -E make_directory build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="/root/torch/install/bin/.." -DCMAKE_INSTALL_PREFIX="/root/torch/install/lib/luarocks/rocks/tbc/scm-1" && make
   
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/gcc
-- Check for working C compiler: /usr/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/g++
-- Check for working CXX compiler: /usr/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found Torch7 in /root/torch/install
-- Performing Test COMPILER_SUPPORTS_CXX11
-- Performing Test COMPILER_SUPPORTS_CXX11 - Success
-- Found CUDA: /usr/local/cuda (found version "8.0") 
-- CUDA Found
-- Autodetected CUDA architecture(s): 5.2 5.2 5.2 5.2 5.2 5.2 5.2 5.2
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/luarocks_tbc-scm-1-3148/TemporalConvolutionTBC/build
[ 50%] Building NVCC (Device) object lib/CMakeFiles/THTBC.dir//./THTBC_generated_init_cuda.cu.o
-- Removing /tmp/luarocks_tbc-scm-1-3148/TemporalConvolutionTBC/build/lib/CMakeFiles/THTBC.dir//./THTBC_generated_init_cuda.cu.o
/usr/bin/cmake -E remove /tmp/luarocks_tbc-scm-1-3148/TemporalConvolutionTBC/build/lib/CMakeFiles/THTBC.dir//./THTBC_generated_init_cuda.cu.o
-- Generating dependency file: /tmp/luarocks_tbc-scm-1-3148/TemporalConvolutionTBC/build/lib/CMakeFiles/THTBC.dir//THTBC_generated_init_cuda.cu.o.NVCC-depend
/usr/local/cuda/bin/nvcc -M -D__CUDACC__ /tmp/luarocks_tbc-scm-1-3148/TemporalConvolutionTBC/lib/init_cuda.cu -o /tmp/luarocks_tbc-scm-1-3148/TemporalConvolutionTBC/build/lib/CMakeFiles/THTBC.dir//THTBC_generated_init_cuda.cu.o.NVCC-depend -ccbin /usr/bin/gcc -m64 --std c++11 -DTORCH_TBC_CUDA -DTHTBC_EXPORTS -Xcompiler ,\"-fPIC\",\"-O3\",\"-DNDEBUG\" -std c++11 -DNVCC -I/tmp/luarocks_tbc-scm-1-3148/TemporalConvolutionTBC/lib -I/usr/local/cuda/include -I/root/torch/install/include -I/root/torch/install/include/TH -I/usr/local/cuda/include -I/root/torch/install/include/THC
nvcc fatal   : redefinition of argument 'std'
CMake Error at THTBC_generated_init_cuda.cu.o.cmake:207 (message):
  Error generating
  /tmp/luarocks_tbc-scm-1-3148/TemporalConvolutionTBC/build/lib/CMakeFiles/THTBC.dir//./THTBC_generated_init_cuda.cu.o


make[2]: *** [lib/CMakeFiles/THTBC.dir/./THTBC_generated_init_cuda.cu.o] \u9519\u8bef 1
make[1]: *** [lib/CMakeFiles/THTBC.dir/all] \u9519\u8bef 2
make: *** [all] \u9519\u8bef 2

Error: Failed installing dependency: https://raw.githubusercontent.com/torch/rocks/master/tbc-scm-1.rockspec - Build error: Failed building.

**Comment by lqfarmer** [comment]
My system:
centos 7

**Comment by duyvuleo** [comment]
I tried the method you mentioned, e.g.,
export CMAKE_LIBRARY_PATH=$CMAKE_LIBRARY_PATH:/home/vhoang2/tools/OpenBLAS/include:/home/vhoang2/tools/OpenBLAS/lib
But it did not work for my case as well. See the following error message:

> Missing dependencies for fairseq:
> torchnet
> visdom
> torchnet-sequential
> tbc
> nccl
> tds
> 
> Using https://raw.githubusercontent.com/torch/rocks/master/torchnet-scm-1.rockspec... switching to 'build' mode
> 
> Missing dependencies for torchnet:
> tds >= 1.0
> 
> Using https://raw.githubusercontent.com/torch/rocks/master/tds-scm-1.rockspec... switching to 'build' mode
> Cloning into 'tds'...
> remote: Counting objects: 32, done.
> remote: Compressing objects: 100% (29/29), done.
> remote: Total 32 (delta 5), reused 10 (delta 1), pack-reused 0
> Receiving objects: 100% (32/32), 23.14 KiB | 0 bytes/s, done.
> Resolving deltas: 100% (5/5), done.
> Checking connectivity... done.
> -- The C compiler identification is GNU 5.4.0
> -- The CXX compiler identification is GNU 5.4.0
> -- Check for working C compiler: /usr/bin/cc
> -- Check for working C compiler: /usr/bin/cc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Check for working CXX compiler: /usr/bin/c++
> -- Check for working CXX compiler: /usr/bin/c++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Found Torch7 in /home/vhoang2/torch/install
> -- Configuring done
> -- Generating done
> CMake Warning:
>   Manually-specified variables were not used by the project:
> 
>     CMAKE_LIBRARY_PATH
> 
> 
> -- Build files have been written to: /tmp/luarocks_tds-scm-1-4162/tds/build.luarocks
> Scanning dependencies of target tds
> [ 16%] Building C object CMakeFiles/tds.dir/tds_utils.c.o
> [ 33%] Building C object CMakeFiles/tds.dir/tds_elem.c.o
> [ 50%] Building C object CMakeFiles/tds.dir/tds_hash.c.o
> [ 66%] Building C object CMakeFiles/tds.dir/tds_vec.c.o
> [ 83%] Building C object CMakeFiles/tds.dir/tds_atomic_counter.c.o
> make[2]: *** No rule to make target '/opt/OpenBLAS/lib/libopenblas.so', needed by 'libtds.so'.  Stop.
> CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/tds.dir/all' failed
> make[1]: *** [CMakeFiles/tds.dir/all] Error 2
> Makefile:127: recipe for target 'all' failed
> make: *** [all] Error 2
> 
> Error: Failed installing dependency: https://raw.githubusercontent.com/torch/rocks/master/torchnet-scm-1.rockspec - Failed installing dependency: https://raw.githubusercontent.com/torch/rocks/master/tds-scm-1.rockspec - Build error: Failed building.

**Comment by jgehring** [comment]
@duyvuleo yeah your new OpenBLAS installation is not being picked up. I'm not sure how to fix this, but maybe you can try doing a fresh torch install in another directory with [torch/distro](https://github.com/torch/distro)?

@lqfarmer this looks like an issue that was filed against the TBC repo recently: https://github.com/gchanan/TemporalConvolutionTBC/issues/2.

**Comment by duyvuleo** [comment]
I figured out the issue by changing the default path to OpenBLAS in Torch installation directory, e.g., 

> install/share/cmake/torch/TorchExports-release.cmake:  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "/opt/OpenBLAS/lib/;rt;m

into

> install/share/cmake/torch/TorchExports-release.cmake:  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "/usr/lib/libopenblas.so;rt;m

The installation is successful; but not sure this is a proper way to do.

**Comment by SuperWu090** [comment]
@jgehring I have the same problem as @lqfarmer, it seems that the problem of tbc has not been solved in gchanan/TemporalConvolutionTBC#2.

**Comment by kobikun** [comment]
@lqfarmer  
I tried like this
```
git clone git://github.com/gchanan/TemporalConvolutionTBC.git
cd TemporalConvolutionTBC
```
and edit `./rocks/tbc-scm-1.rockspec`

```
build = {
   type = "command",
   build_command = [[
cmake -E make_directory build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="$(LUA_BINDIR)/.." -DCMAKE_INSTALL_PREFIX="$(PREFIX)" && \
cp ./lib/CMakeFiles/THTBC.dir/THTBC_generated_init_cuda.cu.o.cmake ./lib/CMakeFiles/THTBC.dir/THTBC_generated_init_cuda.cu.o.cmake.tmp && \
cat ./lib/CMakeFiles/THTBC.dir/THTBC_generated_init_cuda.cu.o.cmake.tmp | sed 's/--std;c++11;//g' > ./lib/CMakeFiles/THTBC.dir/THTBC_generated_init_cuda.cu.o.cmake &&
$(MAKE)
   ]],
   install_command = "cd build && $(MAKE) install"
}
```

make and install.

```
luarocks make ./rocks/tbc-scm-1.rockspec
```

**Comment by lqfarmer** [comment]
@kobikun @jgehring 
my problem has been solved. I do following steps:
cd ./fairseq
git clone git://github.com/gchanan/TemporalConvolutionTBC.git
cd TemporalConvolutionTBC

vim ./lib/CMakeLists.txt

changed line : CUDA_ADD_LIBRARY(THTBCMODULE${SRC}OPTIONS -std C++11) # module for mac os x support into CUDA_ADD_LIBRARY(THTBCMODULE${SRC})
then works;
my system : centos 7

**Comment by ghost** [comment]
I have followed @lqfarmer's steps without success, does that means that the issue is still present in TemporalConvolutionTBC despite [gchanan's pull request](https://github.com/gchanan/TemporalConvolutionTBC/pull/4)?
